from typing import List
from app.schemas.review_result import ReviewResultDTO, ReviewIssue, SuggestedTestCase

class CommentFormatter:
    @staticmethod
    def format_issues_table(issues: List[ReviewIssue]) -> str:
        """
        Format a list of review issues into a Markdown table.
        """
        if not issues:
            return "_Không phát hiện vấn đề rõ ràng._\n"
        
        table = "| File | Line | Level | Issue | Suggestion |\n|---|---|---|---|---|\n"
        for issue in issues:
            # Clean newlines from cells to avoid breaking the markdown table
            file_clean = str(issue.file).replace("\n", " ")
            line_clean = str(issue.line).replace("\n", " ")
            level_clean = str(issue.level).replace("\n", " ")
            issue_clean = str(issue.issue).replace("\n", "<br>")
            sug_clean = str(issue.suggestion).replace("\n", "<br>")
            table += f"| `{file_clean}` | `{line_clean}` | **{level_clean}** | {issue_clean} | {sug_clean} |\n"
        return table

    @staticmethod
    def format_test_cases(test_cases: List[SuggestedTestCase]) -> str:
        """
        Format suggested test cases as a bulleted list.
        """
        if not test_cases:
            return "_Không phát hiện đề xuất test case._\n"
        
        output = ""
        for tc in test_cases:
            name_clean = str(tc.name).replace("\n", " ")
            prio_clean = str(tc.priority).replace("\n", " ")
            desc_clean = str(tc.description).replace("\n", " ")
            output += f"- **{name_clean}** (Priority: **{prio_clean}**): {desc_clean}\n"
        return output

    @classmethod
    def format_comment(cls, result: ReviewResultDTO) -> str:
        """
        Format the overall review result into a clean, markdown review comment.
        """
        bugs_table = cls.format_issues_table(result.potential_bugs)
        security_table = cls.format_issues_table(result.security_issues)
        smells_table = cls.format_issues_table(result.code_smells)
        performance_table = cls.format_issues_table(result.performance_issues)
        test_cases_list = cls.format_test_cases(result.suggested_test_cases)
        
        can_merge_text = "Yes" if result.merge_recommendation.can_merge else "No"
        
        comment = f"""## AI Code Review Result

### Summary
{result.summary}

### Risk Level
**{result.risk_level}**

### Potential Bugs
{bugs_table}

### Security Issues
{security_table}

### Code Smells
{smells_table}

### Performance Issues
{performance_table}

### Suggested Test Cases
{test_cases_list}

### Merge Recommendation
**Can merge:** {can_merge_text}

**Reason:** {result.merge_recommendation.reason}

---
*Generated by AI GitHub Code Review Platform*
"""
        return comment
